behaviors:
    Agent:
        trainer_type: ppo
        self_play:
            window: 10
        time_horizon: 300
        max_steps: 1e7
        summary_freq: 50000
engine_settings:
  width: 640
  height: 360